version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: always
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    networks:
      - backend
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    container_name: api_container
    env_file:
      - ./todo-api/.env
    networks:
      - backend
    ports:
      - "3001:3001"
    depends_on:
      - db

  front:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: front_container
    ports:
      - "80:80"


networks:
  backend:
    driver: bridge  